### ISSUE TITLE
Multiselect field getting prefilled with search term

### ISSUE THREAD

**Issue by pearlyong** [opengovsg/design-system#500]
After you search and select an option, that search term gets prefilled in the field - see video for example

https://github.com/opengovsg/design-system/assets/28617936/67a8cc29-60f8-4b51-97a5-602f02916d0d

**Comment by karrui** [comment]
Is this not expected behaviour? When you click away from the input, any input string will get cleared. The reason for this is so that users can select multiple items with a single search string @pearlyong. Ping me if still unexpected behaviour, or I can add an option for users to select which behaviour they want.
